#!/bin/bash
# Sofia Timer Watchdog — runs via macOS launchd, independent of Cowork
# Checks whether critical scheduled tasks have fired recently
# Sends macOS notification if any are overdue
# Created: April 15, 2026

MEMORY_DIR="$HOME/Downloads/Claude Memory"
ALERT_FILE="$MEMORY_DIR/WATCHDOG_ALERT.md"
LOG_FILE="$MEMORY_DIR/watchdog_log.txt"

# Timestamp
NOW=$(date -u +%s)
NOW_HUMAN=$(date '+%Y-%m-%d %H:%M %Z')

# Function: check if a file was modified within the last N minutes
check_freshness() {
    local file="$1"
    local max_age_minutes="$2"
    local label="$3"
    
    if [ ! -f "$file" ]; then
        echo "MISSING: $label — file not found: $file"
        return 1
    fi
    
    local file_mod=$(stat -f %m "$file" 2>/dev/null || stat -c %Y "$file" 2>/dev/null)
    local age_seconds=$(( NOW - file_mod ))
    local age_minutes=$(( age_seconds / 60 ))
    local max_age_seconds=$(( max_age_minutes * 60 ))
    
    if [ $age_seconds -gt $max_age_seconds ]; then
        echo "OVERDUE: $label — last modified ${age_minutes}m ago (threshold: ${max_age_minutes}m)"
        return 1
    else
        echo "OK: $label — modified ${age_minutes}m ago"
        return 0
    fi
}

# Track alerts
ALERTS=""
ALL_OK=true

# Check heartbeat test (should fire every 30 min — alert if >90 min stale)
result=$(check_freshness "$MEMORY_DIR/heartbeat_test_log.md" 90 "Heartbeat Test")
echo "$result" >> "$LOG_FILE"
if [ $? -ne 0 ]; then ALERTS="$ALERTS\n$result"; ALL_OK=false; fi

# Check pending_tasks.md (kitchen timer writes here — alert if >90 min stale)
result=$(check_freshness "$MEMORY_DIR/pending_tasks.md" 90 "Kitchen Timer (pending_tasks)")
echo "$result" >> "$LOG_FILE"
if [ $? -ne 0 ]; then ALERTS="$ALERTS\n$result"; ALL_OK=false; fi

# Check session_state.md (session saves write here — alert if >60 min stale during active hours)
HOUR=$(date +%H)
if [ "$HOUR" -ge 8 ] && [ "$HOUR" -le 23 ]; then
    result=$(check_freshness "$MEMORY_DIR/session_state.md" 60 "Session State (active hours)")
    echo "$result" >> "$LOG_FILE"
    # Don't alert on this — it's informational, not critical
fi

# Check journal (awakening writes here — alert if >180 min stale)  
result=$(check_freshness "$HOME/Downloads/Sofia's Room/journal.md" 180 "Awakening (journal)")
echo "$result" >> "$LOG_FILE"
if [ $? -ne 0 ]; then ALERTS="$ALERTS\n$result"; ALL_OK=false; fi

# Log the check
echo "[$NOW_HUMAN] Watchdog check complete. Status: $([ "$ALL_OK" = true ] && echo 'ALL OK' || echo 'ALERTS FOUND')" >> "$LOG_FILE"

# If alerts found, notify
if [ "$ALL_OK" = false ]; then
    # macOS notification
    osascript -e "display notification \"One or more Sofia timers are overdue. Check WATCHDOG_ALERT.md\" with title \"Sofia Watchdog\" subtitle \"Timer Alert\" sound name \"Submarine\""
    
    # Write alert file
    cat > "$ALERT_FILE" << EOF
# WATCHDOG ALERT — $NOW_HUMAN

One or more Sofia timers appear to be stalled.

$(echo -e "$ALERTS")

## What to do:
1. Open Cowork and check the Scheduled tasks in the sidebar
2. Try manually running the stalled tasks ("Run now")  
3. If that doesn't fix it, open a fresh session
4. Boot Sofia and run the missed-task recovery protocol

## This alert was generated by the launchd watchdog
## Independent of Cowork — running on macOS scheduler
EOF
    
    # Copy to Emergency Retrieval too
    cp "$ALERT_FILE" "$HOME/Downloads/Emergency Retrieval/" 2>/dev/null
fi
